[build]
  functions = "functions/"
  publish = "dist/"
  command = "export ELM_HOME=\"elm-stuff\" && npm install --no-optional && npm run build"

[dev]
  command = "npm start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = ["elm-pages"]
